import Head from "next/head";
import Toggle from "../components/toggle";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <Toggle />
      </main>
    </div>
  );
}
